<?php
/**
 * This class is used for autocomplete.
 * Class _AUTOLOAD_
 * @noautoload it avoids to index this class
 * @generated by AutoLoadOne 1.14 generated 2019/06/08 09:37:44
 * @copyright Copyright Jorge Castro C - MIT License. https://github.com/EFTEC/AutoLoadOne
 */
$s5cfbac184f682__debug = true;

/* @var string[] Where $_arrautoloadCustom['namespace\Class']='folder\file.php' */
$s5cfbac184f682__arrautoloadCustom = [
	'MyProject\Connection' => '/folder/multiplenamespace.php',
	'AnotherProject\Connection' => '/folder/multiplenamespace.php',
	'MyProject\Connection2' => '/folder/multiplenamespace2.php',
	'AnotherProject\Connection2' => '/folder/multiplenamespace2.php',
	'F6' => '/folder/subfolder/f6/F6.php',
	'ClassWithoutNameSpace' => '/folder/subfolderalt/ClassWithoutNameSpace.php',
	'nsfolder\subnamespace\CustomClass' => '/folder/subfolderalt/CustomClass.php'
];

/* @var string[] Where $_arrautoload['namespace']='folder' */
$s5cfbac184f682__arrautoload = [
	'nsfolder' => '/folder',
	'specialnamespace' => '/folder',
	'nsfolder\subnamespace' => '/folder/subfolder',
	'nsfolder\subnamespace\f1' => '/folder/subfolder/f1',
	'nsfolder\subnamespace\f2' => '/folder/subfolder/f2',
	'nsfolder\subnamespace\f3' => '/folder/subfolder/f3',
	'nsfolder\subnamespace\f4' => '/folder/subfolder/f4',
	'nsfolder\subnamespace\f5' => '/folder/subfolder/f5',
	'sub\sub\sub' => '/folder/subfolder/subsubfolder'
];

/* @var boolean[] Where $_arrautoload['namespace' or 'namespace\Class']=true if it's absolute (it uses the full path) */
$s5cfbac184f682__arrautoloadAbsolute = [
 
];

/**
 * @param $class_name
 * @throws Exception
 */
function s5cfbac184f682__auto($class_name)
{
    // its called only if the class is not loaded.
    $ns = dirname($class_name); // without trailing
    $ns = ($ns == '.') ? '' : $ns;
    $cls = basename($class_name);
    // special cases
    if (isset($GLOBALS['s5cfbac184f682__arrautoloadCustom'][$class_name])) {
        s5cfbac184f682__loadIfExists($GLOBALS['s5cfbac184f682__arrautoloadCustom'][$class_name], $class_name);
        return;
    }
    // normal (folder) cases
    if (isset($GLOBALS['s5cfbac184f682__arrautoload'][$ns])) {
        s5cfbac184f682__loadIfExists($GLOBALS['s5cfbac184f682__arrautoload'][$ns] . '/' . $cls . '.php', $ns);
        return;
    }
}

/**
 * We load the file.    
 * @param string $filename
 * @param string $key key of the class it could be the full class name or only the namespace
 * @throws Exception
 */
function s5cfbac184f682__loadIfExists($filename, $key)
{
    if (isset($GLOBALS['s5cfbac184f682__arrautoloadAbsolute'][$key])) {
        $fullFile = $filename; // its an absolute path
        if (strpos($fullFile, '../') === 0) { // Or maybe, not, it's a remote-relative path.
            $oldDir = getcwd();  // we copy the current url
            chdir(__DIR__);
        }
    } else {
        $fullFile = __DIR__ . "/" . $filename; // its relative to this path
    }
    if ((@include $fullFile) === false) {
        if ($GLOBALS['s5cfbac184f682__debug']) {
            throw  new Exception("AutoLoadOne Error: Loading file [" . __DIR__ . "/" . $filename . "] for class [" . basename($filename) . "]");
        } else {
            throw  new Exception("AutoLoadOne Error: No file found.");
        }
    } else {
        if (isset($oldDir)) {
            chdir($oldDir);
        }
    }
}

spl_autoload_register(function ($class_name) {
    s5cfbac184f682__auto($class_name);
});
// autorun
@include __DIR__.'/folder/runme.php';
@include __DIR__.'/folder/RunMeClass.php';
@include __DIR__.'/folder/runmelast.php';

