<?php
/**
 * This class is used for autocomplete.
 * Class _AutoLoad
 * @noautoload it avoids to index this class
 * @generated by AutoLoadOne 1.1 generated 2018/06/26 03:49:14
 * @copyright Copyright Jorge Castro C - MIT License. https://github.com/EFTEC/AutoLoadOne
 */
class _AutoLoad
{
    var $debug=false;
    private $_arrautoloadCustom = array(
		'MyProject\Connection' => '/../multiplenamespace.php',
		'AnotherProject\Connection' => '/../multiplenamespace.php',
		'MyProject\Connection2' => '/../multiplenamespace2.php',
		'AnotherProject\Connection2' => '/../multiplenamespace2.php',
		'ClassWithoutNameSpace' => '/../subfolderalt/ClassWithoutNameSpace.php',
		'folder\subfolder\CustomClass' => '/../subfolderalt/CustomClass.php',
		'ComposerAutoloaderInitfa359d287c4cb4296ff953e38b0f842a' => '/../../../vendor/composer/autoload_real.php',
		'Composer\Autoload\ComposerStaticInitfa359d287c4cb4296ff953e38b0f842a' => '/../../../vendor/composer/autoload_static.php'
    );
    private $_arrautoload = array(
		'folder' => '/../../folder',
		'folder\subfolder' => '/../subfolder',
		'sub\sub\sub' => '/../subfolder/subsubfolder',
		'Composer\Autoload' => '/../../../vendor/composer'
    );
    /**
     * _AutoLoad constructor.
     * @param bool $debug
     */
    public function __construct($debug=false)
    {
        $this->debug = $debug;
    }
    /**
     * @param $class_name
     * @throws Exception
     */
    public function auto($class_name) {
        // its called only if the class is not loaded.
        $ns = dirname($class_name); // without trailing
        $ns=($ns==".")?"":$ns;        
        $cls = basename($class_name);
        // special cases
        if (isset($this->_arrautoloadCustom[$class_name])) {
            $this->loadIfExists($this->_arrautoloadCustom[$class_name] );
            return;
        }
        // normal (folder) cases
        if (isset($this->_arrautoload[$ns])) {
            $this->loadIfExists($this->_arrautoload[$ns] . "\\" . $cls . ".php");
            return;
        }
    }

    /**
     * @param $filename
     * @throws Exception
     */
    public function loadIfExists($filename)
    {
        if((@include __DIR__."\\".$filename) === false) {
            if ($this->debug) {
                throw  new Exception("AutoLoadOne Error: Loading file [".__DIR__."\\".$filename."] for class [".basename($filename)."]");
            } else {
                throw  new Exception("AutoLoadOne Error: No file found.");
            }
        }
    }
} // end of the class _AutoLoad
if (defined('_AUTOLOADONEDEBUG')) {
    $_autoLoad=new _AutoLoad(_AUTOLOADONEDEBUG);
} else {
    $_autoLoad=new _AutoLoad(false);
}
spl_autoload_register(function ($class_name)
{
    global $_autoLoad;
    $_autoLoad->auto($class_name);
});